name: Project X Consultancy
favicon: null
layout_spectrum: 0.2044866809155792
typography_spectrum: 0.6189746703021228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.9218064132146537
  saturation: 0.1801594018470496
  rhythmicContrast: 0.051426104037091136
purpose: []
